import numpy as np
import pandas as pd
import pickle as pkl
from mu2e import mu2e_ext_path
# globals
import os
import sys
fpath = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.abspath(os.path.join(fpath, '..', '..', 'configs')))
from model_globals import noise, noise_str, phony_curl, phony_curl_str

# add a curled field ?
def Field_With_Curl(x, y, z, Cx = 10., Cy = 10., Cz = 10.):
    return np.array([Cx * y, -Cy * x, Cz * np.ones_like(z)])

def curl_of_Field(x, y, z, Cx, Cy, Cz):
    #return np.ones_like(x) * (-Cy - Cx)
    return -Cy - Cx

if __name__=='__main__':
    # set random seed for reproducibility
    seed = 1313
    print(f'Using random seed: {seed}\n')
    np.random.seed(seed)
    #### load initial dataframe (generated by helicalc and Opera)
    fname0 = mu2e_ext_path+'Bmaps/docdb-48750/Mu2e_V13_DSCylFMSAll_Helicalc_All_Coils_All_Busbars_Rebar.Mu2E.p'
    print(f'Loading original field map (from helicalc and Opera): {fname0}')
    df0 = pd.read_pickle(fname0)
    print('Done.\n')
    #### add noise
    print('Adding noise to field...')
    fname1 = fname0.replace('.Mu2E.p', f'{noise_str}.Mu2E.p')
    df1 = df0.copy()
    dBx, dBy, dBz = np.random.normal(loc=0.0, scale=noise, size=(3, len(df1)))
    df1.loc[:, 'Bx'] = df1.loc[:, 'Bx'] + dBx
    df1.loc[:, 'By'] = df1.loc[:, 'By'] + dBy
    df1.loc[:, 'Bz'] = df1.loc[:, 'Bz'] + dBz
    print(f'(global)noise={noise}, mean (dBx, dBy, dBz) = ({np.mean(dBx):0.3f},'\
          +f'{np.mean(dBy):0.3f}, {np.mean(dBz):0.3f}); RMS (Bx, By, Bz) = ('\
          +f'{np.std(dBx, ddof=1):0.3f}, {np.std(dBy, ddof=1):0.3f}, {np.std(dBz, ddof=1):0.3f}).')
    # reevaluate Br, Bphi to propagate the noise
    df1.eval('Bphi = -Bx*sin(Phi)+By*cos(Phi)', inplace=True)
    df1.eval('Br = Bx*cos(Phi)+By*sin(Phi)', inplace=True)
    # save
    print(f'Saving to: {fname1}.')
    df1.to_pickle(fname1)
    print('Done.\n')
    #### external points only, with the noise
    fname3 = fname1.replace('.Mu2E.p', f'_external_fit.Mu2E.p')
    df3 = df1.copy()
    map_ext = ((df3.HP == "BP5") | ((df3.Z <= 4.251) | (df3.Z >= 13.849)))
    fit_points = False * np.ones(len(df3), dtype=bool)
    fit_points[map_ext] = True
    df3.loc[:, 'fit_point'] = fit_points
    # save
    print(f'Saving to: {fname3}.')
    df3.to_pickle(fname3)
    print('Done.\n')
    #### phony curl, with the noise
    print('Adding curl to field...')
    fname4 = fname1.replace('.Mu2E.p', f'{phony_curl_str}.Mu2E.p')
    df4 = df1.copy()
    Cx = - phony_curl / 2.
    Cy = - phony_curl / 2.
    Cz = 0.
    X = df4.X
    Y = df4.Y
    Z = df4.Z
    dBx, dBy, dBz = Field_With_Curl(X, Y, Z, Cx=Cx, Cy=Cy, Cz=Cz)
    expected_curl_Z = curl_of_Field(X, Y, Z, Cx, Cy, Cz)
    print(f'(global)phony_curl={phony_curl}, expected_curl_Z={expected_curl_Z}')
    df4.loc[:, 'Bx'] = df4.loc[:, 'Bx'] + dBx
    df4.loc[:, 'By'] = df4.loc[:, 'By'] + dBy
    df4.loc[:, 'Bz'] = df4.loc[:, 'Bz'] + dBz
    # reevaluate Br, Bphi to propagae the curled field
    df4.eval('Bphi = -Bx*sin(Phi)+By*cos(Phi)', inplace=True)
    df4.eval('Br = Bx*cos(Phi)+By*sin(Phi)', inplace=True)
    # save
    print(f'Saving to: {fname4}.')
    df4.to_pickle(fname4)
    print('Done.\n')
    #### busbars only (with connectors)
    #### load initial dataframe (generated by helicalc)
    fname0_bus = mu2e_ext_path+'Bmaps/docdb-48750/Mu2e_V13_DSCylFMSAll_Helicalc_No_Coils_All_Busbars.Mu2E.p'
    print(f'Loading original field map with busbars only (from helicalc): {fname0_bus}')
    df0_bus = pd.read_pickle(fname0_bus)
    print('Done.\n')
    #### add noise
    print('Adding noise to field...')
    fname6 = fname0_bus.replace('.Mu2E.p', f'{noise_str}.Mu2E.p')
    df6 = df0_bus.copy()
    dBx_b, dBy_b, dBz_b = np.random.normal(loc=0.0, scale=noise, size=(3, len(df6)))
    df6.loc[:, 'Bx'] = df6.loc[:, 'Bx'] + dBx_b
    df6.loc[:, 'By'] = df6.loc[:, 'By'] + dBy_b
    df6.loc[:, 'Bz'] = df6.loc[:, 'Bz'] + dBz_b
    print(f'(global)noise={noise}, mean (dBx, dBy, dBz) = ({np.mean(dBx_b):0.3f},'\
          +f'{np.mean(dBy_b):0.3f}, {np.mean(dBz_b):0.3f}); RMS (Bx, By, Bz) = ('\
          +f'{np.std(dBx_b, ddof=1):0.3f}, {np.std(dBy_b, ddof=1):0.3f}, {np.std(dBz_b, ddof=1):0.3f}).')
    # reevaluate Br, Bphi to propagate the noise
    df6.eval('Bphi = -Bx*sin(Phi)+By*cos(Phi)', inplace=True)
    df6.eval('Br = Bx*cos(Phi)+By*sin(Phi)', inplace=True)
    # save
    print(f'Saving to: {fname6}.')
    df6.to_pickle(fname6)
    print('Done.\n')
    #### DS coils only (with connectors)
    #### load initial dataframe (generated by helicalc)
    fname0_coil = mu2e_ext_path+'Bmaps/docdb-48750/Mu2e_V13_DSCylFMSAll_Helicalc_All_Coils_No_Busbars.Mu2E.p'
    print(f'Loading original field map with busbars only (from helicalc): {fname0_coil}')
    df0_coil = pd.read_pickle(fname0_coil)
    print('Done.\n')
    #### add noise
    print('Adding noise to field...')
    fname7 = fname0_coil.replace('.Mu2E.p', f'{noise_str}.Mu2E.p')
    df7 = df0_coil.copy()
    dBx_c, dBy_c, dBz_c = np.random.normal(loc=0.0, scale=noise, size=(3, len(df7)))
    df7.loc[:, 'Bx'] = df7.loc[:, 'Bx'] + dBx_c
    df7.loc[:, 'By'] = df7.loc[:, 'By'] + dBy_c
    df7.loc[:, 'Bz'] = df7.loc[:, 'Bz'] + dBz_c
    print(f'(global)noise={noise}, mean (dBx, dBy, dBz) = ({np.mean(dBx_c):0.3f},'\
          +f'{np.mean(dBy_c):0.3f}, {np.mean(dBz_c):0.3f}); RMS (Bx, By, Bz) = ('\
          +f'{np.std(dBx_c, ddof=1):0.3f}, {np.std(dBy_c, ddof=1):0.3f}, {np.std(dBz_c, ddof=1):0.3f}).')
    # reevaluate Br, Bphi to propagate the noise
    df7.eval('Bphi = -Bx*sin(Phi)+By*cos(Phi)', inplace=True)
    df7.eval('Br = Bx*cos(Phi)+By*sin(Phi)', inplace=True)
    # save
    print(f'Saving to: {fname7}.')
    df7.to_pickle(fname7)
    print('Done.\n')
    #### HPC mag unc
    sf_file = os.path.join(os.path.abspath(os.path.join(fpath, '..', '..', 'configs')), 'HPCMagUnc_SFs.p')
    params_HPCMag = pkl.load(open(sf_file, 'rb'))
    fname8 = fname1.replace('.Mu2E.p', f'_HPCMagUnc.Mu2E.p')
    df8 = df1.copy()
    for k, SF in params_HPCMag.items():
        map_ = (df8.HP == k)
        for i in ['x', 'y', 'z', 'r', 'phi']:
            df8.loc[map_, f'B{i}'] *= SF
    # save
    print(f'Saving to: {fname8}.')
    df8.to_pickle(fname8)
    print('Done.\n')
    #### SparseZPhi
    fname9 = fname1.replace('.Mu2E.p', '_SparseZPhi.Mu2E.p')
    df9 = df1.copy()
    print('Removing half of phi steps...')
    print(f'len(df9) before = {len(df9)}')
    df9 = df9[np.any(np.isclose(df9.Phi.values[:, np.newaxis], np.sort(df9.Phi.unique())[::2][np.newaxis, :]), axis=1)]
    df9.reset_index(drop=True, inplace=True)
    print(f'len(df9) after = {len(df9)}')
    print('Removing half of z steps...')
    print(f'len(df9) before = {len(df9)}')
    ###df0 = df0[np.any(np.isclose(df0.Z.values[:, np.newaxis], np.sort(df0.Z.unique())[::2][np.newaxis, :]), axis=1)]
    # splitting props
    df9 = df9[np.any(np.isclose(df9.Z.values[:, np.newaxis], np.sort(np.concatenate([df9.query('HP == "BP1"').Z.unique()[::2], df9.query('HP == "SP1"').Z.unique()[::2]]))[np.newaxis, :]), axis=1)]
    df9.reset_index(drop=True, inplace=True)
    print(f'len(df9) after = {len(df9)}')
    # save
    print(f'Saving to: {fname9}.')
    df9.to_pickle(fname9)
    print('Done.\n')
    #### HPCMagUnc, SparseZPhi
    fname10 = fname1.replace('.Mu2E.p', '_HPCMagUnc_SparseZPhi.Mu2E.p')
    df10 = df8.copy()
    print('Removing half of phi steps...')
    print(f'len(df10) before = {len(df10)}')
    df10 = df10[np.any(np.isclose(df10.Phi.values[:, np.newaxis], np.sort(df10.Phi.unique())[::2][np.newaxis, :]), axis=1)]
    df10.reset_index(drop=True, inplace=True)
    print(f'len(df10) after = {len(df10)}')
    print('Removing half of z steps...')
    print(f'len(df10) before = {len(df10)}')
    ###df0 = df0[np.any(np.isclose(df0.Z.values[:, np.newaxis], np.sort(df0.Z.unique())[::2][np.newaxis, :]), axis=1)]
    # splitting props
    df10 = df10[np.any(np.isclose(df10.Z.values[:, np.newaxis], np.sort(np.concatenate([df10.query('HP == "BP1"').Z.unique()[::2], df10.query('HP == "SP1"').Z.unique()[::2]]))[np.newaxis, :]), axis=1)]
    df10.reset_index(drop=True, inplace=True)
    print(f'len(df10) after = {len(df10)}')
    # save
    print(f'Saving to: {fname10}.')
    df10.to_pickle(fname10)
    print('Done.\n')
    print('Field map prep is complete.')
