import numpy as np
import pandas as pd
from mu2e import mu2e_ext_path
# globals
import os
import sys
fpath = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.abspath(os.path.join(fpath, '..', '..', 'configs')))
from globals import noise, noise_str, phony_curl, phony_curl_str

# add a curled field ?
def Field_With_Curl(x, y, z, Cx = 10., Cy = 10., Cz = 10.):
    return np.array([Cx * y, -Cy * x, Cz * np.ones_like(z)])

def curl_of_Field(x, y, z, Cx, Cy, Cz):
    #return np.ones_like(x) * (-Cy - Cx)
    return -Cy - Cx

if __name__=='__main__':
    # set random seed for reproducibility
    seed = 1313
    print(f'Using random seed: {seed}\n')
    np.random.seed(seed)
    #### load initial dataframe (generated by helicalc and Opera)
    fname0 = mu2e_ext_path+'Bmaps/PINN_paper/Mu2e_V13_DSCylFMSAll_Helicalc_All_Coils_All_Busbars_Rebar.Mu2E.p'
    print(f'Loading original field map (from helicalc and Opera): {fname0}')
    df0 = pd.read_pickle(fname0)
    print('Done.\n')
    #### add noise
    print('Adding noise to field...')
    fname1 = fname0.replace('.Mu2E.p', f'{noise_str}.Mu2E.p')
    df1 = df0.copy()
    dBx, dBy, dBz = np.random.normal(loc=0.0, scale=noise, size=(3, len(df1)))
    df1.loc[:, 'Bx'] = df1.loc[:, 'Bx'] + dBx
    df1.loc[:, 'By'] = df1.loc[:, 'By'] + dBy
    df1.loc[:, 'Bz'] = df1.loc[:, 'Bz'] + dBz
    print(f'(global)noise={noise}, mean (dBx, dBy, dBz) = ({np.mean(dBx):0.3f},'\
          +f'{np.mean(dBy):0.3f}, {np.mean(dBz):0.3f}); RMS (Bx, By, Bz) = ('\
          +f'{np.std(dBx, ddof=1):0.3f}, {np.std(dBy, ddof=1):0.3f}, {np.std(dBz, ddof=1):0.3f}).')
    # reevaluate Br, Bphi to propagate the noise
    df1.eval('Bphi = -Bx*sin(Phi)+By*cos(Phi)', inplace=True)
    df1.eval('Br = Bx*cos(Phi)+By*sin(Phi)', inplace=True)
    # save
    print(f'Saving to: {fname1}.')
    df1.to_pickle(fname1)
    print('Done.\n')
    #### external points only, with the noise
    fname3 = fname1.replace('.Mu2E.p', f'_external_fit.Mu2E.p')
    df3 = df1.copy()
    map_ext = ((df3.HP == "BP5") | ((df3.Z <= 4.251) | (df3.Z >= 13.849)))
    fit_points = False * np.ones(len(df3), dtype=bool)
    fit_points[map_ext] = True
    df3.loc[:, 'fit_point'] = fit_points
    # save
    print(f'Saving to: {fname3}.')
    df3.to_pickle(fname3)
    print('Done.\n')
    #### phony curl, with the noise
    print('Adding curl to field...')
    fname4 = fname1.replace('.Mu2E.p', f'{phony_curl_str}.Mu2E.p')
    df4 = df1.copy()
    Cx = - phony_curl / 2.
    Cy = - phony_curl / 2.
    Cz = 0.
    X = df3.X
    Y = df3.Y
    Z = df3.Z
    dBx, dBy, dBz = Field_With_Curl(X, Y, Z, Cx=Cx, Cy=Cy, Cz=Cz)
    expected_curl_Z = curl_of_Field(X, Y, Z, Cx, Cy, Cz)
    print(f'(global)phony_curl={phony_curl}, expected_curl_Z={expected_curl_Z}')
    df4.loc[:, 'Bx'] = df4.loc[:, 'Bx'] + dBx
    df4.loc[:, 'By'] = df4.loc[:, 'By'] + dBy
    df4.loc[:, 'Bz'] = df4.loc[:, 'Bz'] + dBz
    # reevaluate Br, Bphi to propagae the curled field
    df4.eval('Bphi = -Bx*sin(Phi)+By*cos(Phi)', inplace=True)
    df4.eval('Br = Bx*cos(Phi)+By*sin(Phi)', inplace=True)
    # save
    print(f'Saving to: {fname4}.')
    df4.to_pickle(fname4)
    print('Done.\n')
    print('Field map prep is complete.')
